# FROM apache/airflow:2.3.2
FROM apache/airflow:slim-2.3.3-python3.8

USER root
RUN apt-get update -y
RUN apt-get update && apt-get install libpq-dev -y

USER airflow
COPY requirements_0.txt .
RUN pip install --no-cache-dir -r requirements_0.txt