FROM taufferconsulting/flowui-airflow-worker-base

USER root
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

USER airflow
COPY config.toml flowui/operators_repository/
COPY operators flowui/operators_repository/operators
COPY .flowui flowui/operators_repository/.flowui
RUN source flowui_env/bin/activate \
    && pip install --no-cache-dir opencv-python scipy boto3