from flowui.base_operator import BaseOperator
from .model import OperatorModel


class ExampleOperator(BaseOperator):

    def operator_function(self, operator_model: OperatorModel):
        # The BaseOperator class provides a set of convenience self variables ready to be used
        # to get the unique id for this task run
        self.run_id
        
        # to get the path where files generated by this task run should be stored
        self.results_path

        # a dict containing xcom data from upstream tasks
        self.upstream_tasks
        
        # a dict containing airflow context data
        self.airflow_context
        
        # a method that allows for logging messages on this task run log
        self.logger

        # to push results to XCom, simply return a xcom dictionary
        xcom_obj = {
            "message": "Task successfully completed!",
            "other_results": dict()
        }
        return xcom_obj